"""initial schema

Revision ID: 13e10a37c311
Revises: 
Create Date: 2026-08-24 13:01:54.174039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13e10a37c311'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'extension', 'email', 'seed')", name='ck_applications_source_valid'),
    sa.CheckConstraint("status IN ('saved', 'applied', 'screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_applications_status_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_role'), 'applications', ['role'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('saved', 'applied', 'screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_application_events_from_status_valid'),
    sa.CheckConstraint("source IN ('manual', 'extension', 'email', 'seed')", name='ck_application_events_source_valid'),
    sa.CheckConstraint("to_status IS NULL OR to_status IN ('saved', 'applied', 'screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_application_events_to_status_valid'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_application_id'), 'audit_log', ['application_id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body_excerpt', sa.String(length=300), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(length=32), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company_hint', sa.String(length=255), nullable=True),
    sa.Column('match_status', sa.String(length=32), nullable=False),
    sa.Column('matched_application_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("match_status IN ('matched', 'unmatched', 'ambiguous')", name='ck_email_events_match_status_valid'),
    sa.CheckConstraint("signal_type IN ('confirmation', 'interview', 'rejection', 'offer', 'unknown')", name='ck_email_events_signal_type_valid'),
    sa.CheckConstraint('classification_confidence >= 0 AND classification_confidence <= 1', name='ck_email_events_confidence_range'),
    sa.CheckConstraint('length(body_excerpt) <= 300', name='ck_email_events_body_excerpt_maxlen'),
    sa.ForeignKeyConstraint(['matched_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', name='uq_email_events_message_id')
    )
    op.create_index(op.f('ix_email_events_message_id'), 'email_events', ['message_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('application_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('email_event_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('proposed_status', sa.String(length=32), nullable=False),
    sa.Column('status_at_proposal', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("proposed_status IN ('saved', 'applied', 'screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_proposals_proposed_status_valid'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_proposals_status_valid'),
    sa.CheckConstraint("status_at_proposal IN ('saved', 'applied', 'screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_proposals_status_at_proposal_valid'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_proposals_confidence_range'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_event_id'], ['email_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_event_id', name='uq_proposals_email_event_id')
    )
    op.create_index(op.f('ix_proposals_application_id'), 'proposals', ['application_id'], unique=False)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_application_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_email_events_message_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_audit_log_application_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_role'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
